GLOBAL:
    TIMEZONE: "Europe/Prague"
    LOGFILE: "-"
    PIDFILE: "/tmp/jetconf.pid"
    PERSISTENT_CHANGES: false
    LOG_LEVEL: "debug"
    LOG_DBG_MODULES: ["usr_conf_data_handlers", "knot_api", "nacm", "data"]
    YANG_LIB_DIR: "/home/deploy/jetconf/jetconf_jukebox/"
    DATA_JSON_FILE: "/home/deploy/jetconf/jetconf-jukebox/example-data.json"
    BACKEND_PACKAGE: "jetconf_jukebox"

HTTP_SERVER:
    DOC_ROOT: "/home/deploy/jetconf/data/doc-root"
    DOC_DEFAULT_NAME: "index.html"
    API_ROOT: "/restconf"
    SERVER_NAME: "jetconf-h2"

    SERVER_SSL_CERT: "/home/deploy/jetconf/data/server.crt"
    SERVER_SSL_PRIVKEY: "/home/deploy/jetconf/data/server.key"
    CA_CERT: "/home/deploy/jetconf/data/ca.pem"
    DBG_DISABLE_CERTS: true

NACM:
    ALLOWED_USERS: ["lojza@mail.cz"]
